# PyTorch Basics: Tensors & Gradients

This tutorial covers the following topics:

* Introductions to PyTorch tensors
* Tensor operations and gradients
* Interoperability between PyTorch and Numpy
* How to use the PyTorch documentation site

Let's import the `torch` module to get started.

In [1]:
import torch

## Tensors

At its core, PyTorch is a library for processing tensors. A tensor is a number, vector, matrix, or any n-dimensional array. Let's create a tensor with number, vector, matrix and 3D-array.

In [7]:
t1 = torch.tensor(4.)            # Number
t2 = torch.tensor([1., 2, 3, 4]) # Vector
t3 = torch.tensor([[5., 6], 
                   [7, 8], 
                   [9, 10]])     # Matrix
# 3-dimensional array
t4 = torch.tensor([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.]]])            # 3D-Array
print(t1,t1.dtype)
print(t2,t2.dtype)
print(t3,t3.dtype)
print(t4,t4.dtype)

tensor(4.) torch.float32
tensor([1., 2., 3., 4.]) torch.float32
tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]]) torch.float32
tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]]) torch.float32


Tensors can have any number of dimensions and different lengths along each dimension. We can inspect the length along each dimension using the `.shape` property of a tensor.

In [10]:
print(t1.shape,t2.shape,t3.shape)

torch.Size([]) torch.Size([4]) torch.Size([3, 2])


Note that it's not possible to create tensors with an improper shape.

In [11]:
# This will throw error if you run
# t5 = torch.tensor([[5., 6, 11], 
#                    [7, 8], 
#                    [9, 10]])
# t5


A `ValueError` is thrown because the lengths of the rows `[5., 6, 11]` and `[7, 8]` don't match.

## Tensor operations and gradients

We can combine tensors with the usual arithmetic operations. Let's look at an example:

In [12]:
# Create tensors.
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

We've created three tensors: `x`, `w`, and `b`, all numbers. `w` and `b` have an additional parameter `requires_grad` set to `True`. We'll see what it does in just a moment. Let's create a new tensor `y` by combining these tensors.

In [13]:
# Arithmetic operations
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

As expected, `y` is a tensor with the value `3 * 4 + 5 = 17`. What makes PyTorch unique is that we can automatically compute the derivative of `y` w.r.t. the tensors that have `requires_grad` set to `True` i.e. w and b. This feature of PyTorch is called _autograd_ (automatic gradients).

To compute the derivatives, we can invoke the `.backward` method on our result `y`.

In [15]:
# Compute derivatives
y.backward()

The derivatives of `y` with respect to all the input tensors are stored in the `.grad` property of the respective tensors. i.e (w and b)

In [16]:
# Display gradients
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


As expected, `dy/dw` has the same value as `x`, i.e., `3`, and `dy/db` has the value `1`. Note that `x.grad` is `None` because `x` doesn't have `requires_grad` set to `True`.

## Tensor functions

Apart from arithmetic operations, the `torch` module also contains many functions for creating and manipulating tensors. Let's look at some examples.

In [23]:
t6 = torch.full((3, 2), 42) # Create a tensor with a fixed value for every element
t7 = torch.cat((t3, t6)) # Concatenate two tensors with compatible shapes
t8 = torch.sin(t7) # Compute the sin of each element
t9 = t8.reshape(-1, 2, 2) # Change the shape of a tensor
t6,t7,t8,t9

(tensor([[42, 42],
         [42, 42],
         [42, 42]]),
 tensor([[ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.],
         [42., 42.],
         [42., 42.],
         [42., 42.]]),
 tensor([[-0.9589, -0.2794],
         [ 0.6570,  0.9894],
         [ 0.4121, -0.5440],
         [-0.9165, -0.9165],
         [-0.9165, -0.9165],
         [-0.9165, -0.9165]]),
 tensor([[[-0.9589, -0.2794],
          [ 0.6570,  0.9894]],
 
         [[ 0.4121, -0.5440],
          [-0.9165, -0.9165]],
 
         [[-0.9165, -0.9165],
          [-0.9165, -0.9165]]]))

You can learn more about tensor operations here: https://pytorch.org/docs/stable/torch.html . Experiment with some more tensor functions and operations using the empty cells below.

In [21]:
t10=torch.arange(20)
t10_rs=t10.reshape(2,5,2)
t10_rs_rs=t10_rs.reshape(5,4)
t10,t10_rs,t10_rs_rs

(tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19]),
 tensor([[[ 0,  1],
          [ 2,  3],
          [ 4,  5],
          [ 6,  7],
          [ 8,  9]],
 
         [[10, 11],
          [12, 13],
          [14, 15],
          [16, 17],
          [18, 19]]]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]))

## Interoperability with Numpy

Instead of reinventing the wheel, PyTorch interoperates well with Numpy to leverage its existing ecosystem of tools and libraries.

Here's how we create an array in Numpy and transform it to torch tensor:

In [29]:
import numpy as np

x = np.array([[1, 2], [3, 4.]]) # numpy array creation
y = torch.from_numpy(x) # get torch tensor from the numpy array.
z = y.numpy() # get back to numpy array
x,y,z

(array([[1., 2.],
        [3., 4.]]),
 tensor([[1., 2.],
         [3., 4.]], dtype=torch.float64),
 array([[1., 2.],
        [3., 4.]]))

Keep in mind that `from_numpy()` method do not create a new copy of the data. It just access the same numpy array and treat it as torch tensor. So any change in original numpy array will reflect also in the torch tensor and vice versa.

In [34]:
x[:,0]=1
x,y

(array([[1., 2.],
        [1., 4.]]),
 tensor([[1., 2.],
         [1., 4.]], dtype=torch.float64))

The interoperability between PyTorch and Numpy is essential because most datasets you'll work with will likely be read and preprocessed as Numpy arrays.

You might wonder why we need a library like PyTorch at all since Numpy already provides data structures and utilities for working with multi-dimensional numeric data. There are two main reasons:

1. **Autograd**: The ability to automatically compute gradients for tensor operations is essential for training deep learning models.
2. **GPU support**: While working with massive datasets and large models, PyTorch tensor operations can be performed efficiently using a Graphics Processing Unit (GPU). Computations that might typically take hours can be completed within minutes using GPUs.

We'll leverage both these features of PyTorch extensively in this tutorial series.

## Summary and Further Reading

Try out this assignment to learn more about tensor operations in PyTorch: https://jovian.ai/aakashns/01-tensor-operations


This tutorial covers the following topics:

* Introductions to PyTorch tensors
* Tensor operations and gradients
* Interoperability between PyTorch and Numpy


You can learn more about PyTorch tensors here: https://pytorch.org/docs/stable/tensors.html. 


The material in this series is inspired by:

* [PyTorch Tutorial for Deep Learning Researchers](https://github.com/yunjey/pytorch-tutorial) by Yunjey Choi 
* [FastAI development notebooks](https://github.com/fastai/fastai_docs/tree/master/dev_nb) by Jeremy Howard. 

With this, we complete our discussion of tensors and gradients in PyTorch, and we're ready to move on to the next topic: [Gradient Descent & Linear Regression](https://jovian.ai/aakashns/02-linear-regression).